services:
  # Application Postgres Database
  arachne-datanode-postgres:
    image: postgres:15.5-alpine
    platform: linux/amd64
    pull_policy: always
    container_name: arachne-datanode-postgres
    restart: always
    logging:
      options:
        max-size: 100m
    shm_size: "4g"
    networks:
      - arachne-network
    ports:
      - "5432:5432" # Port mapping (host:container)
    volumes:
      - arachne-pg-data:/var/lib/postgresql/data # Volume mount for Arachne PG data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Initialization script
    environment:
      POSTGRES_USER: ohdsi-user
      POSTGRES_PASSWORD: ohdsi-password

  # Execution Engine
  arachne-execution-engine:
    image: odysseusinc/execution_engine:2.7.1
    pull_policy: always
    platform: linux/amd64
    container_name: arachne-execution-engine
    restart: always
    networks:
      - arachne-network
    ports:
      - "127.0.0.1:8888:8888"  # Port mapping (host:container)
    volumes:
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/executions:/etc/executions
    environment:
      - applyRuntimeDependenciesComparisonLogic=true
      - libraries.location.strategus=strategus
      - DOCKER_IMAGE_DEFAULT=odysseusinc/r-hades:latest
      - DOCKER_IMAGE_FILTER=odysseusinc/r-hades(.+)
      - ANALYSIS_MOUNT=/tmp/executions
      - RUNTIMESERVICE_DIST_VERBOSE_LOG=true
      - RUNTIMESERVICE_DIST_ARCHIVEFOLDER=/runtimes/
      - RUNTIMESERVICE_DIST_DEFAULTDESCRIPTORFILE=descriptor_base.json

    # Arachne Central (Community Edition)
  arachne-central:
    image: odysseusinc/arachne-central-ce:latest
    platform: linux/amd64
    container_name: arachne-central
    pull_policy: always
    restart: always
    networks:
      - arachne-network
    env_file:
      - central.env  # Environment variables file
    ports:
      - "127.0.0.1:8080:8080"  # Localhost port 8443 maps to internal port 8443
      - "127.0.0.1:8983:8983"  # Localhost port 8983 maps to internal port 8983
    depends_on:
      - arachne-datanode-postgres


  # Arachne Datanode Service
  arachne-datanode:
    image: odysseusinc/arachne-datanode-ce:latest
    pull_policy: always
    container_name: arachne-datanode
    platform: linux/amd64
    restart: always
    networks:
      - arachne-network
    ports:
      - "8880:8880" # Port mapping (host:container)
    volumes:
      - arachne-datanode-files:/var/arachne/files  # Volume mount for Arachne data
    env_file:
      - datanode.env  # Environment variables file
    depends_on:
      - arachne-datanode-postgres
      - arachne-execution-engine
      - arachne-central

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    platform: linux/amd64
    pull_policy: always
    networks:
      - arachne-network
    ports:
      - "127.0.0.1:5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - arachne-datanode-postgres

# Volumes for the services
volumes:
  arachne-pg-data:
  arachne-datanode-files:
  pgadmin-data:

# Network definition
networks:
  arachne-network:
